# To set up a development environment using conda run:
#
#   conda env create -f environment.yml
#   conda activate bipca-experiment
#   pip install -e .
name: bipca-experiment
channels:
  - conda-forge
  - pytorch
  - bioconda
dependencies:
  - python=3.9
  - pip
  - mkl
  - cpuonly
  - pytorch
  - matplotlib
  - pandas
  - scipy
  - scikit-learn
  - numpy
  - seaborn
  - statsmodels
  - numba
  - pytables
  - igraph
  - leidenalg
  - xarray
  - scanpy
  - threadpoolctl
  - plotly
  - opentsne
  - netcdf4
  - bedtools
  - htslib
  - tqdm
  - ccache
  - jupyterlab
  - jupyter
  - pybedtools 
  - zarr
  - sphinx
  - pip:
    - --requirement requirements.txt

  
